name: Frontend Linting Workflow

on:  
  # every push, included 4 testing, TODO: rm
  push:
    branches:
      - '*'
  # on every pull req to a main branch...
  pull_request:
    branches: 
      - 'main'

#
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout /public
        uses: actions/checkout@v4
        with: # fetch only public/ folder 
          sparse-checkout: |
            public
