name: Frontend Linting Workflow

on:  
  push:
    branches:
      - '*'
  # pull_request:
  #   branches: [ "main" ]

#
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout /public
        uses: actions/checkout@v4
        # with: # fetch only public/ folder 
        #   sparse-checkout: |
        #     public
