name: Frontend Linting Workflow

on:  
  # every push, included 4 testing, TODO: rm
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - 'main'

#
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout /public
        uses: actions/checkout@v4
        # with: # fetch only public/ folder 
        #   sparse-checkout: |
        #     public
